[package]
name = "color_analyzer"
version = "0.1.0"
authors = ["Tyler G <tyler@geerydev.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"

[dependencies.rocket_contrib]
version = "*"
features = ["json"]
