FROM color_analyzer

ENV RUST_BACKTRACE 1

# RUN rustup update && \
#     rustup self update && \
#     rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy

RUN cargo install cargo-watch

ENTRYPOINT ["cargo", "watch", "-x", "run"]
