FROM color_analyzer

RUN rustup update && \
    rustup self update && \
    # rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy && \
    cargo install cargo-watch

ENV RUST_BACKTRACE 1
ENTRYPOINT ["cargo", "watch", "-x", "run"]
